version: '3'

services:
  postgres:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: zhmot
      POSTGRES_PASSWORD: secretische
    ports:
      - "8320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: