version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: zhmot
      POSTGRES_PASSWORD: secretische
    #ports:
    #  - "8320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  bands:
    build:
      context: bands_service
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    restart: no
  util:
    container_name: util
    depends_on: 
      - discovery
    build:
      context: util_service
      dockerfile: Dockerfile
    restart: no
    #ports:
    #  - "7010:7010"
  discovery:
    container_name: discovery
    build:
      context: discovery
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8761:8761"
  gateway:
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8765:8765"

volumes:
  postgres_data: