version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: zhmot
      POSTGRES_PASSWORD: secretische
    ports:
      - "8300:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  bands:
    container_name: bands
    build:
      context: bands_service
      dockerfile: Dockerfile
    restart: no
    ports:
      - "7008:7008"
  util:
    container_name: util
    depends_on: 
      - discovery
    build:
      context: util_service
      dockerfile: Dockerfile
    restart: no
    ports:
      - "7010:7010"
  discovery:
    container_name: discovery
    build:
      context: discovery
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8761:8761"
volumes:
  postgres_data: