server:
  port: 7008
  servlet:
    context-path: /
    session:
      timeout: 600s
  error:
    include-message: always

spring:
  application:
    name: bands
#  datasource:
#    url: jdbc:postgresql://localhost:8320/music
#    username: zhmot
#    password: secretische
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
        
eureka:
  instance:
    metadata-map:
      zone: ru-1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka