server:
  port: 7008
  servlet:
    context-path: /
    session:
      timeout: 600s
  error:
    include-message: always
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/bands.p12
    key-store-password: 123456
    key-alias: bands
    enabled: true

spring:
  application:
    name: bands
  datasource:
    url: jdbc:postgresql://postgres:5432/music
    username: zhmot
    password: secretische
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

logging:
  level:
    org:
      springframework:
        security: DEBUG
        
eureka:
  instance:
    metadata-map:
      zone: ru-1
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka