server:
  port: 7008
  servlet:
    context-path: /
    session:
      timeout: 600s
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:8320/music
    username: zhmot
    password: secretische
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

logging:
  level:
    org:
      springframework:
        security: DEBUG