server:
  port: 7011
  servlet:
    context-path: /
    session:
      timeout: 600s
  error:
    include-message: always

spring:
  application:
    name: UTIL_SOAP
  profiles:
    active: cfg
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin
      
bands:
  api:
    base: http://BANDS