server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: 
        - id: bands
          uri: http://127.0.0.1:7008
          predicates:
            - Path=/bands/**
          filters:
            - RewritePath=/bands/(?<segment>.*), /$\{segment}
        - id: util
          uri: http://127.0.0.1:7010
          predicates:
            - Path=/util/**
          filters:
            - RewritePath=/util/(?<segment>.*), /$\{segment}
      enabled: true


eureka:
  instance:
    metadata-map:
      zone: ru-1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
logging:
  level:
    org.springframework.cloud.gateway: DEBUG