server:
  port: 443
  error:
    include-message: always
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/util.p12
    key-store-password: 123456
    key-alias: util

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: 
        - id: bands
          uri: http://127.0.0.1:7008
          predicates:
            - Path=/bands/**
          filters:
            - RewritePath=/bands/(?<segment>.*), /$\{segment}
        - id: util
          uri: http://127.0.0.1:7010
          predicates:
            - Path=/util/**
          filters:
            - RewritePath=/util/(?<segment>.*), /$\{segment}
      enabled: true


eureka:
  instance:
    metadata-map:
      zone: ru-1
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
      
logging:
  level:
    org.springframework.cloud.gateway: DEBUG