server:
  port: 7010
  servlet:
    context-path: /grammy
    session:
      timeout: 600s
  error:
    include-message: always
  ssl:
    enabled: true
    
    key-store-type: PKCS12
    key-store: classpath:keystore/util.p12
    key-store-password: 123456
    key-alias: util
    
    trust-store-type: PKCS12
    trust-store: classpath:truststore/bands.p12
    trust-store-password: 123456

spring:
  application:
    name: util
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      
eureka:
  instance:
    metadata-map:
      zone: ru-1
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
      
ribbon:
  eureka:
    enabled: true